import os
import warnings
from dataclasses import dataclass, field

from p4gitsync.lfs.lfs_pointer_utils import format_lfs_pointer


@dataclass
class LfsConfig:
    enabled: bool = False
    extensions: list[str] = field(
        default_factory=lambda: [
            ".uasset",
            ".umap",
            ".fbx",
            ".png",
            ".jpg",
            ".jpeg",
            ".tga",
            ".psd",
            ".wav",
            ".mp3",
            ".ogg",
            ".mp4",
            ".bin",
            ".dll",
            ".so",
            ".exe",
        ]
    )
    size_threshold_bytes: int = 100 * 1024  # 100KB
    # 확장자 화이트리스트에 없어도 P4 file_type 이 binary 인 파일을 크기 임계로
    # LFS 라우팅할지 여부. 기본 비활성(확장자 전용, 기존 동작 유지).
    auto_detect_binary: bool = False
    # binary 자동 라우팅에 쓸 크기 임계. None 이면 size_threshold_bytes 를 사용.
    binary_size_threshold_bytes: int | None = None
    lockable_extensions: list[str] = field(
        default_factory=lambda: [
            ".uasset",
            ".umap",
        ]
    )
    # True면 generate_gitattributes에 줄바꿈/텍스트 정규화 규칙을 함께 출력
    # (CRLF/LF 혼란·대량 diff 방지). 엔진 무관 일반 규칙.
    text_normalization: bool = False
    server_type: str = "builtin"  # "builtin" (GitHub/GitLab) | "self-hosted"
    server_url: str = (
        ""  # self-hosted LFS 서버 URL (server_type="self-hosted"일 때 사용)
    )
    auth_type: str = "git-credential"  # "git-credential" | "token" | "basic"
    auth_token: str = ""
    auth_username: str = ""
    auth_password: str = ""

    def generate_gitattributes(self) -> str:
        """LFS 대상 확장자에 대한 .gitattributes 내용 생성.

        text_normalization=True면 LFS 규칙 앞에 줄바꿈/텍스트 정규화 규칙을
        추가한다(플랫폼 간 CRLF/LF 혼란과 대량 diff 방지).
        """
        lines: list[str] = []
        if self.text_normalization:
            lines.extend([
                "# Text/EOL normalization (auto-generated by p4gitsync)",
                "* text=auto eol=lf",
                "*.sh text eol=lf",
                "*.bat text eol=crlf",
                "*.cmd text eol=crlf",
                "*.ps1 text eol=crlf",
                "",
            ])
        lines.append("# Git LFS tracking rules (auto-generated by p4gitsync)")
        lockable_set = set(self.lockable_extensions)
        for ext in sorted(self.extensions):
            attr = f"*{ext} filter=lfs diff=lfs merge=lfs -text"
            if ext in lockable_set:
                attr += " lockable"
            lines.append(attr)
        return "\n".join(lines) + "\n"

    def generate_lfsconfig(self) -> str | None:
        """self-hosted LFS 서버 설정 시 .lfsconfig 내용 생성. builtin이면 None."""
        if self.server_type == "builtin" and self.auth_type == "git-credential":
            return None
        lines = ["[lfs]"]
        if self.server_type == "self-hosted" and self.server_url:
            if self.auth_type == "basic" and self.auth_username:
                url = self.server_url.replace("://", f"://{self.auth_username}@")
                lines.append(f"    url = {url}")
            else:
                lines.append(f"    url = {self.server_url}")
        if self.auth_type == "token":
            lines.append("    access = basic")
        return "\n".join(lines) + "\n"

    def is_lfs_target_ext(self, path: str) -> bool:
        """경로의 확장자가 LFS 확장자 화이트리스트에 있는지 확인."""
        _, ext = os.path.splitext(path)
        return ext.lower() in self.extensions

    def is_lfs_target(self, path: str) -> bool:
        """경로의 확장자가 LFS 대상인지 확인(확장자 전용, 하위호환 유지)."""
        return self.is_lfs_target_ext(path)

    @property
    def effective_binary_threshold(self) -> int:
        """binary 자동 라우팅에 적용할 크기 임계(바이트).

        binary_size_threshold_bytes 가 지정되면 그 값을, 아니면 size_threshold_bytes 를 쓴다.
        """
        if self.binary_size_threshold_bytes is not None:
            return self.binary_size_threshold_bytes
        return self.size_threshold_bytes

    def route_to_lfs(
        self,
        *,
        git_path: str,
        file_type: str,
        size: int | None,
        sniff_head: bytes | None = None,
    ) -> bool:
        """파일을 LFS 로 보낼지 결정한다.

        확장자 매칭 OR (binary 타입 AND size >= 임계). 판정 로직은
        lfs_routing.decide_lfs_route 에 위임한다.
        """
        from p4gitsync.lfs.lfs_routing import decide_lfs_route

        return decide_lfs_route(
            git_path=git_path,
            file_type=file_type,
            size=size,
            cfg=self,
            sniff_head=sniff_head,
        )

    def is_lockable(self, path: str) -> bool:
        """P4 +l (exclusive lock) 타입에 해당하는 LFS lockable 파일인지 확인."""
        _, ext = os.path.splitext(path)
        return ext.lower() in self.lockable_extensions

    def inject_credentials(self, repo_path: str) -> None:
        """auth_type에 따라 git credential-store에 인증 정보 주입."""
        if self.auth_type == "git-credential" or not self.server_url:
            return

        from urllib.parse import urlparse
        import subprocess

        parsed = urlparse(self.server_url)
        if self.auth_type == "token":
            username = "token"
            password = self.auth_token
        elif self.auth_type == "basic":
            username = self.auth_username
            password = self.auth_password
        else:
            return

        cred_input = (
            f"protocol={parsed.scheme}\n"
            f"host={parsed.netloc}\n"
            f"username={username}\n"
            f"password={password}\n"
            "\n"
        )
        subprocess.run(
            ["git", "credential", "approve"],
            input=cred_input.encode(),
            cwd=repo_path,
            capture_output=True,
        )

    @staticmethod
    def classify_p4_lock_type(file_type: str) -> bool:
        """P4 파일 타입에 +l (exclusive open) 플래그가 있는지 확인."""
        return "+l" in file_type

    @staticmethod
    def create_lfs_pointer(content: bytes) -> bytes:
        """Deprecated. Use lfs_pointer_utils.format_lfs_pointer() instead."""
        warnings.warn(
            "create_lfs_pointer is deprecated, use lfs_pointer_utils.format_lfs_pointer",
            DeprecationWarning,
            stacklevel=2,
        )
        import hashlib

        oid = hashlib.sha256(content).hexdigest()
        size = len(content)
        return format_lfs_pointer(oid, size)
