import hashlib
import os
from dataclasses import dataclass, field


@dataclass
class LfsConfig:
    enabled: bool = False
    extensions: list[str] = field(default_factory=lambda: [
        ".uasset", ".umap", ".fbx", ".png", ".jpg", ".jpeg",
        ".tga", ".psd", ".wav", ".mp3", ".ogg", ".mp4",
        ".bin", ".dll", ".so", ".exe",
    ])
    size_threshold_bytes: int = 100 * 1024  # 100KB
    lockable_extensions: list[str] = field(default_factory=lambda: [
        ".uasset", ".umap",
    ])
    server_type: str = "builtin"  # "builtin" (GitHub/GitLab) | "self-hosted"
    server_url: str = ""  # self-hosted LFS 서버 URL (server_type="self-hosted"일 때 사용)

    def generate_gitattributes(self) -> str:
        """LFS 대상 확장자에 대한 .gitattributes 내용 생성."""
        lines = ["# Git LFS tracking rules (auto-generated by p4gitsync)"]
        lockable_set = set(self.lockable_extensions)
        for ext in sorted(self.extensions):
            attr = f"*{ext} filter=lfs diff=lfs merge=lfs -text"
            if ext in lockable_set:
                attr += " lockable"
            lines.append(attr)
        return "\n".join(lines) + "\n"

    def generate_lfsconfig(self) -> str | None:
        """self-hosted LFS 서버 설정 시 .lfsconfig 내용 생성. builtin이면 None."""
        if self.server_type != "self-hosted" or not self.server_url:
            return None
        return (
            "# Git LFS config (auto-generated by p4gitsync)\n"
            "[lfs]\n"
            f"\turl = {self.server_url}\n"
        )

    def is_lfs_target(self, path: str) -> bool:
        """경로의 확장자가 LFS 대상인지 확인."""
        _, ext = os.path.splitext(path)
        return ext.lower() in self.extensions

    def is_lockable(self, path: str) -> bool:
        """P4 +l (exclusive lock) 타입에 해당하는 LFS lockable 파일인지 확인."""
        _, ext = os.path.splitext(path)
        return ext.lower() in self.lockable_extensions

    @staticmethod
    def classify_p4_lock_type(file_type: str) -> bool:
        """P4 파일 타입에 +l (exclusive open) 플래그가 있는지 확인."""
        return "+l" in file_type

    @staticmethod
    def create_lfs_pointer(content: bytes) -> bytes:
        """파일 내용으로부터 Git LFS 포인터 파일 생성."""
        sha256 = hashlib.sha256(content).hexdigest()
        size = len(content)
        pointer = (
            f"version https://git-lfs.github.com/spec/v1\n"
            f"oid sha256:{sha256}\n"
            f"size {size}\n"
        )
        return pointer.encode("utf-8")
